In [34]:
#import the required libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Step 1 : Read the Data!

In [35]:
#give path of the source-file and store that path in a variable named census
census = 'D:/junotbok/1st mini project/makeSenseOfCensus.csv'

# Loading the data

You have studied getfromtext in Numpy Classes, now is the time to put it into action :) Below is the half completed code, you have to substitute values for delimiter and skip_header in it for hte data to be properly read into a Data array. The output of the array has been shared with you guys followed by the code block

In [36]:
#data = np.genfromtxt(data_file, delimiter = , skip_header = )
#print("\nData:\n\n ", data)
data = np.genfromtxt(census, delimiter = ',', skip_header = 1)
print("\nData:\n\n ", data)


Data:

  [[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]


# Printing the type of data

In [37]:
#print the type of data
print(type(data))

<class 'numpy.ndarray'>


# Step 2 : Append the Data

A new record [[50,9,4,1,0,0,40,0]] has been given to you. You are supposed to append this new record into the data using np.concatenate()

In [38]:
new_record = [[50,9,4,1,0,0,40,0]]

## Append 'new_record' (given) to 'data' using "np.concatenate()"

In [39]:
print("Original data:")
print(data)
new_record = [[50,9,4,1,0,0,40,0]]
data = np.concatenate((data, new_record))
print("\nUpdated data:")
print(data)

Original data:
[[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]

Updated data:
[[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]
 [50.  9.  4. ...  0. 40.  0.]]


In [40]:
#display after appending the new record at the end of the array.
new_record = [[50,9,4,1,0,0,40,0]]
data = np.concatenate((data, new_record))
print("\nUpdated data:")
print(data)
#in numpy new appended data are always at tthe end of list or array by default 


Updated data:
[[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [39. 13.  4. ...  0. 50.  1.]
 [50.  9.  4. ...  0. 40.  0.]
 [50.  9.  4. ...  0. 40.  0.]]


# Step 3 : Check if it's a young country or old country

 Create a new array called 'age' by taking only age column(age is the column with index 0) of 'census' array.

In [41]:
census = np.genfromtxt('makeSenseOfCensus.csv', delimiter=',')
age = census[:, 0]

Find the max age and store it in a variable called 'max_age'.



In [44]:
#print the max_age
max_age = np.max(age)
#age = age[~np.isnan(age)]
print("Maximum age:", max_age)

Maximum age: 90.0


Find the min age and store it in a variable called 'min_age'.

In [45]:
#print the min_age
min_age = np.min(age)
age = age[~np.isnan(age)]
print("Minimum age:", min_age)

Minimum age: 17.0


Find the mean of the age and store it in a variable called 'age_mean'.

In [46]:
age_mean = np.mean(age)
print("Mean Age:", age_mean)

Mean Age: 38.051


Find the standard deviation of the age and store it in a variable called 'age_std'

In [47]:
#print the age_std
age_std = np.std(age)
print("Standard Age:", age_std)

Standard Age: 13.342803266180612


# Step 4: Let's check the country's race distribution to identify the minorities

Create four different arrays by subsetting 'census' array by Race column(Race is the column with index 2) and save them in 'race_0','race_1', 'race_2', 'race_3' and 'race_4' respectively(Meaning: Store the array where 'race'column has value 0 in 'race_0', so on and so forth)

In [48]:
census = np.genfromtxt('makeSenseOfCensus.csv', delimiter=',')
race = census[:, 2]

In [49]:
race_0 = census[race == 0]
race_1 = census[race == 1]
race_2 = census[race == 2]
race_3 = census[race == 3]
race_4 = census[race == 4]
print("Race_0:", race_0)
print("Race_4:", race_4)

Race_0: [[34.  4.  0.  1.  0.  0. 45.  0.]
 [35. 10.  0.  0.  0.  0. 40.  0.]
 [60.  6.  0.  0.  0.  0. 10.  0.]
 [51.  9.  0.  1.  0.  0. 40.  0.]
 [25. 10.  0.  0.  0.  0. 20.  0.]
 [20.  9.  0.  1.  0.  0. 48.  0.]
 [23. 10.  0.  0.  0.  0. 25.  0.]
 [29.  9.  0.  1.  0.  0. 40.  0.]
 [27. 12.  0.  1.  0.  0. 40.  0.]
 [31. 12.  0.  0.  0.  0. 40.  0.]]
Race_4: [[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]


Store the length of the above created arrays in 'len_0', 'len_1','len_2', 'len_3' and 'len_4' respectively

In [50]:
len_0 = len(race_0)
len_1 = len(race_1)
len_2 = len(race_2)
len_3 = len(race_3)
len_4 = len(race_4)

In [51]:
#len_0
print("Length of race_0:", len_0)

Length of race_0: 10


In [52]:
#len_1
print("Length of race_1:", len_1)

Length of race_1: 27


In [53]:
#len_2
print("Length of race_2:", len_2)

Length of race_2: 110


In [54]:
#len_3
print("Length of race_3:", len_3)

Length of race_3: 6


In [55]:
#len_4
print("Length of race_4:", len_4)

Length of race_4: 847


Find out which is the race with the minimum no. of citizens

In [59]:
race_lengths = {
    0: len_0,
    1: len_1,
    2: len_2,
    3: len_3,
    4: len_4
}
min_race = min(race_lengths, key=race_lengths.get)
print("The race with the minimum number of citizens is:", min_race)

The race with the minimum number of citizens is: 3


Find out which is the race with the maximum no. of citizens

In [60]:
race_length = {
    0: len_0,
    1: len_1,
    2: len_2,
    3: len_3,
    4: len_4
}
max_race = max(race_length, key=race_length.get)
print("The race with maximum citizen is :", max_race)

The race with maximum citizen is : 4


Store the number associated with the minority race in a variable called 'minority_race'(For eg: if "len(race_5)" is the minimum, store 5 in 'minority_race' because that is the index of the race having the least no. of citizens )

In [23]:
minority_race = min(race_length, key=race_length.get)
print("The race with minimum citizen is :", minority_race)

The race with minimum citizen is : 3


Store the number associated with the minority race in a variable called 'majority_race'(For eg: if "len(race_5)" is the minimum, store 5 in 'majority_race' because that is the index of the race having the least no. of citizens )

In [24]:
majority_race = max(race_length, key=race_length.get)
print("The race with maximum citizen is :", majority_race)

The race with maximum citizen is : 4


# Step 5: As per govt. records citizens above 60 should not work more than 25 hours a week. Let us check if the policy is in place

a.Create a new subset array called 'senior_citizens' by filtering 'census' according to age>60 (age is the column with index 0)

[Row,Columns]  :

In [25]:
#from age column, filter out age data > 60
senior_citizens = census[census[:, 0] > 60]
print("Senior citizens:", senior_citizens)

Senior citizens: [[7.9000e+01 1.0000e+01 4.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00
  2.0000e+01 0.0000e+00]
 [6.7000e+01 6.0000e+00 4.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00
  2.0000e+00 0.0000e+00]
 [7.6000e+01 1.4000e+01 4.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00
  4.0000e+01 1.0000e+00]
 [6.1000e+01 9.0000e+00 4.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00
  4.0000e+01 0.0000e+00]
 [7.0000e+01 1.0000e+01 4.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00
  4.0000e+01 0.0000e+00]
 [6.4000e+01 7.0000e+00 4.0000e+00 1.0000e+00 0.0000e+00 2.1790e+03
  4.0000e+01 0.0000e+00]
 [7.1000e+01 1.0000e+01 2.0000e+00 1.0000e+00 0.0000e+00 1.8160e+03
  2.0000e+00 0.0000e+00]
 [6.8000e+01 2.0000e+00 4.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00
  2.0000e+01 0.0000e+00]
 [6.6000e+01 1.1000e+01 4.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00
  2.0000e+01 0.0000e+00]
 [6.4000e+01 2.0000e+00 4.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00
  4.0000e+01 0.0000e+00]
 [9.0000e+01 9.0000e+00 2.0000e+00 1.0000e+00 0.0000e

b.Add all the working hours(working hours is the column with index 6) of 'senior_citizens' and store it in a variable called 'working_hours_sum'

In [63]:
working_hours_sum = np.sum(senior_citizens[:, 6])
print("Total working hours of senior citizens:", working_hours_sum)

Total working hours of senior citizens: 1917.0


c.Find the length of 'senior_citizens' and store it in a variable called 'senior_citizens_len'

In [64]:
senior_citizens_len = senior_citizens.shape[0]

print("Number of senior citizens:", senior_citizens_len)

Number of senior citizens: 61


d. Finally find the average working hours of the senior citizens by dividing 'working_hours_sum' by 'senior_citizens_len' and store it in a variable called 'avg_working hours'.

In [65]:
avg_working_hours = working_hours_sum / senior_citizens_len
print("Average working hours of senior citizens:", avg_working_hours)

Average working hours of senior citizens: 31.42622950819672


e. Print 'avg_working_hours' and see if the govt. policy is followed.

In [69]:
avg_working_hours = working_hours_sum / senior_citizens_len
govt_policy_hours = 25
if avg_working_hours > govt_policy_hours:
    print(" The government policy is not followed.")
else:
    ("The government policy is followed.")

 The government policy is not followed.


# Step 6: Let's check that higher educated people have better pay in general.

Create two new subset arrays called 'high' and 'low' by filtering 'census' according to education-num>10 and education-num<=10 (education-num is the column with index 1) respectively.



In [70]:
high = [row for row in census if row[1] > 10]
low = [row for row in census if row[1] <= 10]

Find the mean of income column(income is the column with index 7) of 'high' array and store it in 'avg_pay_high'. Do the same for 'low' array and store it's mean in 'avg_pay_low'.

In [71]:

high = census[census[:, 1] > 10]
low = census[census[:, 1] <= 10]

In [72]:
avg_pay_high = np.mean(high[:, 7])
avg_pay_low = np.mean(low[:, 7])

In [73]:
print("avg_pay_high Mean:", avg_pay_high)
print("avg_pay_low Mean:", avg_pay_low)

avg_pay_high Mean: 0.42813455657492355
avg_pay_low Mean: 0.13670133729569092
